"""Easy DataFrame access to public data sources relevant to Italy."""

from ._common import DataSourceError
from .geo import (
    attach_administrative_boundaries,
    fetch_administrative_boundaries,
    fetch_administrative_boundary_metadata,
    list_administrative_boundary_divisions,
)
from .sources import (
    fetch_bankitalia_exchange_rates,
    fetch_bdap_data,
    fetch_ckan_resource,
    fetch_ecb_data,
    fetch_eurostat_data,
    fetch_fred_data,
    fetch_inps_data,
    fetch_italian_open_data_resource,
    fetch_istat_data,
    fetch_lombardy_data,
    fetch_oecd_data,
    fetch_opencoesione_data,
    fetch_pnrr_data,
    fetch_socrata_data,
    fetch_world_bank_data,
    get_bdap_dataset_metadata,
    get_ckan_dataset_metadata,
    get_ckan_resource_metadata,
    get_inps_dataset,
    get_inps_dataset_metadata,
    get_italian_open_data_dataset_metadata,
    get_lombardy_dataset_metadata,
    get_socrata_dataset_metadata,
    list_bankitalia_currencies,
    list_bdap_datasets,
    list_ckan_datasets,
    list_ecb_dataflows,
    list_eurostat_dataflows,
    list_inps_datasets,
    list_italian_open_data_datasets,
    list_istat_dataflows,
    list_lombardy_datasets,
    list_oecd_dataflows,
    list_opencoesione_resources,
    list_pnrr_resources,
    list_socrata_datasets,
    list_world_bank_indicators,
    search_fred_series,
)

__all__ = [
    "DataSourceError",
    "fetch_bankitalia_exchange_rates",
    "fetch_bdap_data",
    "fetch_ckan_resource",
    "fetch_ecb_data",
    "fetch_eurostat_data",
    "fetch_fred_data",
    "fetch_inps_data",
    "fetch_italian_open_data_resource",
    "fetch_istat_data",
    "fetch_lombardy_data",
    "fetch_oecd_data",
    "fetch_opencoesione_data",
    "fetch_pnrr_data",
    "fetch_socrata_data",
    "fetch_world_bank_data",
    "attach_administrative_boundaries",
    "fetch_administrative_boundaries",
    "fetch_administrative_boundary_metadata",
    "get_bdap_dataset_metadata",
    "get_ckan_dataset_metadata",
    "get_ckan_resource_metadata",
    "get_inps_dataset",
    "get_inps_dataset_metadata",
    "get_italian_open_data_dataset_metadata",
    "get_lombardy_dataset_metadata",
    "get_socrata_dataset_metadata",
    "list_administrative_boundary_divisions",
    "list_bankitalia_currencies",
    "list_bdap_datasets",
    "list_ckan_datasets",
    "list_ecb_dataflows",
    "list_eurostat_dataflows",
    "list_inps_datasets",
    "list_italian_open_data_datasets",
    "list_istat_dataflows",
    "list_lombardy_datasets",
    "list_oecd_dataflows",
    "list_opencoesione_resources",
    "list_pnrr_resources",
    "list_socrata_datasets",
    "list_world_bank_indicators",
    "search_fred_series",
]

__version__ = "0.1.0"
